#[derive(Debug)]
pub(super) enum SemRule {
    Axiom,
    Lambda,
    BlockMore,
    FuncBlockStmnt,
    FuncParamStop,
    FuncParamMore,
    FuncParamNone,
    FuncParamSome,
    FuncRetNone,
    FuncRetSome,
    FuncParam,
    FuncName,
    FuncRettype,
    Func,
    FuncDecl,
    DeclZoneVar,
    TypeMap,
    StmntRetNone,
    StmntRetSome,
    StmntBlockDoWhile,
    StmntBlockDeclAssign,
    StmntBlockDecl,
    StmntBlockIf,
    Stmnt,
    FuncArgStop,
    FuncArgMore,
    FuncArgNone,
    FuncArgSome,
    StmntRet,
    StmntRead,
    StmntWrite,
    StmntCall,
    StmntAndassign,
    StmntAssign,
    ExprId,
    ExprMap,
    ExprWrap,
    ExprCall,
    ExprOperBinNum,
    ExprOperBinCmp,
    ExprOperBinBool,
    ExprOperUnrBool,
    ExprOperUnrNum,
}

impl SemRule {
    pub(super) const fn from_idx(idx: usize) -> Self {
        match idx {
            0 => SemRule::Axiom,
            1 | 4 => SemRule::Lambda,
            2 | 3 => SemRule::BlockMore,
            5  => SemRule::FuncBlockStmnt,
            6  => SemRule::FuncParamStop,
            7  => SemRule::FuncParamMore,
            8  => SemRule::FuncParamNone,
            9  => SemRule::FuncParamSome,
            10 => SemRule::FuncRetNone,
            11 => SemRule::FuncRetSome,
            12 => SemRule::FuncParam,
            13 => SemRule::FuncName,
            14 => SemRule::FuncRettype,
            15 => SemRule::Func,
            16 => SemRule::StmntRetNone,
            17 => SemRule::StmntRetSome,
            18 => SemRule::DeclZoneVar,
            19..=22 => SemRule::TypeMap,
            23 => SemRule::StmntBlockDoWhile,
            24 => SemRule::StmntBlockDeclAssign,
            25 => SemRule::StmntBlockDecl,
            26 => SemRule::StmntBlockIf,
            27 => SemRule::Stmnt,
            28 => SemRule::FuncArgStop,
            29 => SemRule::FuncArgMore,
            30 => SemRule::FuncArgNone,
            31 => SemRule::FuncArgSome,
            32 => SemRule::StmntRet,
            33 => SemRule::StmntRead,
            34 => SemRule::StmntWrite,
            35 => SemRule::StmntCall,
            36 => SemRule::StmntAndassign,
            37 => SemRule::StmntAssign,
            38 => SemRule::ExprId,
            39..=43 | 46 | 48 | 50 | 52 | 54 | 56 => SemRule::ExprMap,
            44 => SemRule::ExprWrap,
            45 => SemRule::ExprCall,
            49 | 51 => SemRule::ExprOperBinNum,
            53 | 55 => SemRule::ExprOperBinCmp,
            57 => SemRule::ExprOperBinBool,
            47 => SemRule::ExprOperUnrBool,
            59 | 60 => SemRule::ExprOperUnrNum,
            58 => SemRule::FuncDecl,
            _ => panic!("unexpected invalid rule index")
        }
    }
}
